<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN4DWW9g\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN4DWW9g/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN4DWW9g.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN4DWW9g\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN4DWW9g\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N4DWW9g',
    'container.build_id' => 'ed5cfcc1',
    'container.build_time' => 1558968704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN4DWW9g');
