<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ15IRlb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ15IRlb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ15IRlb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ15IRlb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ15IRlb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q15IRlb',
    'container.build_id' => '924c64cc',
    'container.build_time' => 1558977365,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ15IRlb');
