<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0OJ6Gn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0OJ6Gn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM0OJ6Gn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM0OJ6Gn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM0OJ6Gn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M0OJ6Gn',
    'container.build_id' => 'b0540eb0',
    'container.build_time' => 1558995859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0OJ6Gn');
